### ISSUE TITLE
Feature? de-prioritize disconnected reflections

### ISSUE THREAD

**Issue by tschundler** [TheMariday/marimapper#54]
In my "hardmode" tests a few days ago were there are glass surfaces, the mapper has difficulty with reflections. I had to set my camera exposure very low (at least -8ev) for it to not count reflections, eg:

<img width="320" alt="MariMapper - Detector_screenshot_18 12 2024 2" src="https://github.com/user-attachments/assets/ac7c960d-28c3-4c65-9de1-1869cf7790ab" />

in my own mapper, I separate islands of connected pixels, and use the one with the greatest total brightness/size

**Comment by tschundler** [comment]
Some related code, maybe inspiration? (it's been a long while since I touched this)

```
import numpy as np
import cv2
from imutils import contours
from skimage import measure


# perform a connected component analysis on the thresholded
# image, then initialize a mask to store only the "large"
# components
def redblobs(color, thresh):
    labels = measure.label(thresh, connectivity=2, background=0)
    mask = np.zeros(thresh.shape, dtype="uint8")
    # loop over the unique components
    for label in np.unique(labels):
        # if this is the background label, ignore it
        if label == 0:
            continue
        # otherwise, construct the label mask and count the
        # number of pixels 
        shape = labels == label
        numPixels = np.count_nonzero(shape)
        # if the number of pixels in the component is sufficiently
        # large, then add it to our mask of "large blobs"
        if numPixels > 20:

            cmask = np.repeat(shape[:, :, np.newaxis], 3, axis=2)
            numPixels = np.count_nonzero(shape)
            csum = (color.sum(axis=(0,1), where=cmask)/numPixels)
            csum = csum - csum.min()
            csum = csum / csum.max()
            csum = csum * 255.0
            csum = csum.astype(np.uint8)
            if csum[0] != 255:
                continue
            if csum[2] > 100:
                continue
    
            #labelMask = np.zeros(thresh.shape, dtype="uint8")
            mask[shape] = 1

            #mask = cv2.add(mask, labelMask)
    return mask

def hotspots(extractor, n, th = 0.90):
    img = extractor.lin_offsetframe(n)
    #grey= img[:,:,0]
    grey = extractor.lin_greyframe(n)
    color = cv2.GaussianBlur(img, (15, 15), 0)
    blurred = cv2.GaussianBlur(grey, (7, 7), 0)

    hist = grey_histogram(grey, 256)
    threshval = int(np.where((hist.cumsum() / hist.sum()) > th)[0][0] + 256) // 2
    #threshval = int(np.where((hist.cumsum() / hist.sum()) > th)[0][0])
    #threshval = int(np.where((hist.cumsum() / hist.sum()) > 0.95)[0][0])

    [minVal, maxVal, minLoc, maxLoc] = cv2.minMaxLoc(blurred)
    #margin = 0.75# statistics to be calculated using hist data    
    threshval = int( maxVal * th) # in pix value to be extracted


    thresh = cv2.threshold(blurred, threshval, 255, cv2.THRESH_BINARY)[1] #* bmask
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=4)
    return redblobs(color, thresh)
```

The "extractor" does subtraction of the reference frame and masks out parts at are bright in the reference frame before even getting to here. And I guess I must have been getting better results in linear colorspace than srgb? 

Here it looks like that histogram stuff I was mentioning is not what the current code is doing, and instead using 90% of the brightest pixel (after masking blown out areas).

**Comment by TheMariday** [comment]
I assume this wasn't tested with V2.3?

In this version, it uses the contour with the brightest pixel to get the position.

I will have a run through of your extractor though to compare

**Comment by tschundler** [comment]
Correct, this is from `main` branch on the 18th a little over a week ago.  That particular setup I can't test again until after New Years

**Comment by TheMariday** [comment]
No problem! Your comments about reflections was what actually lead me to adjust the detector! Hope that it addresses the reflections

**Comment by TheMariday** [comment]
This should be much improved in v2.3 which can be grabbed with `pipx upgrade marimapper`

Happy to reopen this if the issue is still persisting
